name: Check Java Version

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-java:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Mostrar versão do Java
        run: java -version

      - name: Mostrar versão do Maven
        run: mvn -v
