name: Lint and Test

on:
  workflow_call:
    inputs:
      run_tests:
        required: false
        type: boolean
        default: true
      run_lint:
        required: false
        type: boolean
        default: true

jobs:
  lint:
    if: ${{ inputs.run_lint == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Verificação de estilo (Lint simulado)
        run: echo "Executando lint do código..."

  test:
    if: ${{ inputs.run_tests == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes
        run: mvn test
