name: Lint and Test Workflow

on:
  workflow_call:

jobs:
  lint:
    name: Verificação de Estilo (Lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar Lint com Checkstyle
        run: |
          mvn checkstyle:checkstyle

  test:
    name: Testes Automatizados
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar testes
        run: mvn test
